server:
  port: 8181
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://metaverse.ohgiraffers.com/pjhbsy?serverTimezone=Asia/Seoul
    username: pjhbsy
    password: pjhbsy
  # smtp 설정
  mail:
    host: smtp.naver.com
    port: 465
    username: antjjump@naver.com
    password: antjump123123!
    properties: # 전송을 위한 prop - ssl 신뢰, 권한 등 사용 허가
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
jwt:
  secret: asdfjp298pafo1320efqw0udvnh0er0h412r08byfdq9dsvh02143908hfeqwn80fdqs0nfdqs0n412013rq0nqefn08dfas0das730732g86923


mybatis:
  # mapper.xml location Setting
  mapper-locations: mybatis/mapper/*.xml
  # alias Setting
  type-aliases-package: com.antjump.ant
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info



