export const issuesData = [
  {
    issueId: 1,
    topIssueId: null,
    issueName: "ISSUE-1",
    issueCategory: "태스크",
    issueSummary: "이슈 요약입니다",
    issueStatus: "시작 전",
    fkMembersIssues: null,
    memberName: "없음",
    issuePriority: "S",
    sprintIncludeYn: "N",
    areaCode: 0,
  },
  {
    issueId: 2,
    topIssueId: null,
    issueName: "ISSUE-2",
    issueCategory: "태스크",
    issueSummary: "이슈 요약입니다",
    issueStatus: "시작 전",
    fkMembersIssues: null,
    memberName: "없음",
    issuePriority: "M",
    areaCode: 0,
  },
  {
    issueId: 3,
    topIssueId: null,
    issueName: "ISSUE-3",
    issueCategory: "스토리",
    issueSummary: "이슈 요약입니다",
    issueStatus: "시작 전",
    fkMembersIssues: null,
    memberName: "없음",
    issuePriority: "S",
    areaCode: 0,
  },
  {
    issueId: 4,
    topIssueId: null,
    issueName: "ISSUE-4",
    issueCategory: "태그",
    issueSummary: "이슈 요약입니다",
    issueStatus: "시작 전",
    fkMembersIssues: null,
    memberName: "없음",
    issuePriority: "M",
    areaCode: 0,
  },
  {
    issueId: 5,
    topIssueId: null,
    issueName: "ISSUE-5",
    issueCategory: "태스크",
    issueSummary: "이슈 요약입니다",
    issueStatus: "시작 전",
    fkMembersIssues: null,
    memberName: "없음",
    issuePriority: "M",
    areaCode: 0,
  },
  {
    issueId: 6,
    topIssueId: null,
    issueName: "ISSUE-6",
    issueCategory: "태스크",
    issueSummary: "이슈 요약입니다",
    issueStatus: "시작 전",
    fkMembersIssues: null,
    memberName: "없음",
    issuePriority: "M",
    areaCode: 0,
  },
  {
    issueId: 7,
    topIssueId: null,
    issueName: "ISSUE-7",
    issueCategory: "태스크",
    issueSummary: "이슈 요약입니다",
    issueStatus: "시작 전",
    fkMembersIssues: null,
    memberName: "없음",
    issuePriority: "M",
    areaCode: 0,
  },
  {
    issueId: 8,
    topIssueId: null,
    issueName: "ISSUE-8",
    issueCategory: "태스크",
    issueSummary: "이슈 요약입니다",
    issueStatus: "시작 전",
    fkMembersIssues: null,
    memberName: "없음",
    issuePriority: "M",
    areaCode: 0,
  },
  {
    issueId: 9,
    topIssueId: null,
    issueName: "ISSUE-9",
    issueCategory: "태스크",
    issueSummary: "이슈 요약입니다",
    issueStatus: "시작 전",
    fkMembersIssues: null,
    memberName: "없음",
    issuePriority: "M",
    areaCode: 1,
  },
  {
    issueId: 15,
    topIssueId: null,
    issueName: "ISSUE-15",
    issueCategory: "스토리",
    issueSummary: "이슈 요약입니다",
    issueStatus: "시작 전",
    fkMembersIssues: null,
    memberName: "없음",
    issuePriority: "M",
    areaCode: 1,
  },
  {
    issueId: 10,
    topIssueId: null,
    issueName: "ISSUE-10",
    issueCategory: "태스크",
    issueSummary: "이슈 요약입니다",
    issueStatus: "시작 전",
    fkMembersIssues: null,
    memberName: "없음",
    issuePriority: "M",
    areaCode: 2,
  },
  {
    issueId: 11,
    topIssueId: null,
    issueName: "ISSUE-11",
    issueCategory: "태스크",
    issueSummary: "이슈 요약입니다",
    issueStatus: "시작 전",
    fkMembersIssues: null,
    memberName: "없음",
    issuePriority: "M",
    areaCode: 3,
  },
];
